// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person_data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_person_5fdata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_person_5fdata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_person_5fdata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_person_5fdata_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_person_5fdata_2eproto;
class person_data_fuzz;
class person_data_fuzzDefaultTypeInternal;
extern person_data_fuzzDefaultTypeInternal _person_data_fuzz_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::person_data_fuzz* Arena::CreateMaybeMessage<::person_data_fuzz>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class person_data_fuzz PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:person_data_fuzz) */ {
 public:
  inline person_data_fuzz() : person_data_fuzz(nullptr) {};
  virtual ~person_data_fuzz();

  person_data_fuzz(const person_data_fuzz& from);
  person_data_fuzz(person_data_fuzz&& from) noexcept
    : person_data_fuzz() {
    *this = ::std::move(from);
  }

  inline person_data_fuzz& operator=(const person_data_fuzz& from) {
    CopyFrom(from);
    return *this;
  }
  inline person_data_fuzz& operator=(person_data_fuzz&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const person_data_fuzz& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const person_data_fuzz* internal_default_instance() {
    return reinterpret_cast<const person_data_fuzz*>(
               &_person_data_fuzz_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(person_data_fuzz& a, person_data_fuzz& b) {
    a.Swap(&b);
  }
  inline void Swap(person_data_fuzz* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(person_data_fuzz* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline person_data_fuzz* New() const final {
    return CreateMaybeMessage<person_data_fuzz>(nullptr);
  }

  person_data_fuzz* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<person_data_fuzz>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const person_data_fuzz& from);
  void MergeFrom(const person_data_fuzz& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(person_data_fuzz* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "person_data_fuzz";
  }
  protected:
  explicit person_data_fuzz(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_person_5fdata_2eproto);
    return ::descriptor_table_person_5fdata_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFuzzNameFieldNumber = 2,
    kFuzzIdFieldNumber = 1,
  };
  // required bytes fuzz_name = 2;
  bool has_fuzz_name() const;
  private:
  bool _internal_has_fuzz_name() const;
  public:
  void clear_fuzz_name();
  const std::string& fuzz_name() const;
  void set_fuzz_name(const std::string& value);
  void set_fuzz_name(std::string&& value);
  void set_fuzz_name(const char* value);
  void set_fuzz_name(const void* value, size_t size);
  std::string* mutable_fuzz_name();
  std::string* release_fuzz_name();
  void set_allocated_fuzz_name(std::string* fuzz_name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_fuzz_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_fuzz_name(
      std::string* fuzz_name);
  private:
  const std::string& _internal_fuzz_name() const;
  void _internal_set_fuzz_name(const std::string& value);
  std::string* _internal_mutable_fuzz_name();
  public:

  // required uint64 fuzz_id = 1;
  bool has_fuzz_id() const;
  private:
  bool _internal_has_fuzz_id() const;
  public:
  void clear_fuzz_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 fuzz_id() const;
  void set_fuzz_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_fuzz_id() const;
  void _internal_set_fuzz_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:person_data_fuzz)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fuzz_name_;
  ::PROTOBUF_NAMESPACE_ID::uint64 fuzz_id_;
  friend struct ::TableStruct_person_5fdata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// person_data_fuzz

// required uint64 fuzz_id = 1;
inline bool person_data_fuzz::_internal_has_fuzz_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool person_data_fuzz::has_fuzz_id() const {
  return _internal_has_fuzz_id();
}
inline void person_data_fuzz::clear_fuzz_id() {
  fuzz_id_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 person_data_fuzz::_internal_fuzz_id() const {
  return fuzz_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 person_data_fuzz::fuzz_id() const {
  // @@protoc_insertion_point(field_get:person_data_fuzz.fuzz_id)
  return _internal_fuzz_id();
}
inline void person_data_fuzz::_internal_set_fuzz_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  fuzz_id_ = value;
}
inline void person_data_fuzz::set_fuzz_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_fuzz_id(value);
  // @@protoc_insertion_point(field_set:person_data_fuzz.fuzz_id)
}

// required bytes fuzz_name = 2;
inline bool person_data_fuzz::_internal_has_fuzz_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool person_data_fuzz::has_fuzz_name() const {
  return _internal_has_fuzz_name();
}
inline void person_data_fuzz::clear_fuzz_name() {
  fuzz_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& person_data_fuzz::fuzz_name() const {
  // @@protoc_insertion_point(field_get:person_data_fuzz.fuzz_name)
  return _internal_fuzz_name();
}
inline void person_data_fuzz::set_fuzz_name(const std::string& value) {
  _internal_set_fuzz_name(value);
  // @@protoc_insertion_point(field_set:person_data_fuzz.fuzz_name)
}
inline std::string* person_data_fuzz::mutable_fuzz_name() {
  // @@protoc_insertion_point(field_mutable:person_data_fuzz.fuzz_name)
  return _internal_mutable_fuzz_name();
}
inline const std::string& person_data_fuzz::_internal_fuzz_name() const {
  return fuzz_name_.Get();
}
inline void person_data_fuzz::_internal_set_fuzz_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  fuzz_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void person_data_fuzz::set_fuzz_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  fuzz_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:person_data_fuzz.fuzz_name)
}
inline void person_data_fuzz::set_fuzz_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  fuzz_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:person_data_fuzz.fuzz_name)
}
inline void person_data_fuzz::set_fuzz_name(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  fuzz_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:person_data_fuzz.fuzz_name)
}
inline std::string* person_data_fuzz::_internal_mutable_fuzz_name() {
  _has_bits_[0] |= 0x00000001u;
  return fuzz_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* person_data_fuzz::release_fuzz_name() {
  // @@protoc_insertion_point(field_release:person_data_fuzz.fuzz_name)
  if (!_internal_has_fuzz_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return fuzz_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void person_data_fuzz::set_allocated_fuzz_name(std::string* fuzz_name) {
  if (fuzz_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  fuzz_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fuzz_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:person_data_fuzz.fuzz_name)
}
inline std::string* person_data_fuzz::unsafe_arena_release_fuzz_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:person_data_fuzz.fuzz_name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return fuzz_name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void person_data_fuzz::unsafe_arena_set_allocated_fuzz_name(
    std::string* fuzz_name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (fuzz_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  fuzz_name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      fuzz_name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:person_data_fuzz.fuzz_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_person_5fdata_2eproto
