// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person_data.proto

#include "person_data.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
class person_data_fuzzDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<person_data_fuzz> _instance;
} _person_data_fuzz_default_instance_;
static void InitDefaultsscc_info_person_data_fuzz_person_5fdata_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_person_data_fuzz_default_instance_;
    new (ptr) ::person_data_fuzz();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::person_data_fuzz::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_person_data_fuzz_person_5fdata_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_person_data_fuzz_person_5fdata_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_person_5fdata_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_person_5fdata_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_person_5fdata_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_person_5fdata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::person_data_fuzz, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::person_data_fuzz, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::person_data_fuzz, fuzz_id_),
  PROTOBUF_FIELD_OFFSET(::person_data_fuzz, fuzz_name_),
  1,
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::person_data_fuzz)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_person_data_fuzz_default_instance_),
};

const char descriptor_table_protodef_person_5fdata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021person_data.proto\"6\n\020person_data_fuzz\022"
  "\017\n\007fuzz_id\030\001 \002(\004\022\021\n\tfuzz_name\030\002 \002(\014"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_person_5fdata_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_person_5fdata_2eproto_sccs[1] = {
  &scc_info_person_data_fuzz_person_5fdata_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_person_5fdata_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_person_5fdata_2eproto = {
  false, false, descriptor_table_protodef_person_5fdata_2eproto, "person_data.proto", 75,
  &descriptor_table_person_5fdata_2eproto_once, descriptor_table_person_5fdata_2eproto_sccs, descriptor_table_person_5fdata_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_person_5fdata_2eproto::offsets,
  file_level_metadata_person_5fdata_2eproto, 1, file_level_enum_descriptors_person_5fdata_2eproto, file_level_service_descriptors_person_5fdata_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_person_5fdata_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_person_5fdata_2eproto)), true);

// ===================================================================

void person_data_fuzz::InitAsDefaultInstance() {
}
class person_data_fuzz::_Internal {
 public:
  using HasBits = decltype(std::declval<person_data_fuzz>()._has_bits_);
  static void set_has_fuzz_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_fuzz_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

person_data_fuzz::person_data_fuzz(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:person_data_fuzz)
}
person_data_fuzz::person_data_fuzz(const person_data_fuzz& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  fuzz_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_fuzz_name()) {
    fuzz_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_fuzz_name(),
      GetArena());
  }
  fuzz_id_ = from.fuzz_id_;
  // @@protoc_insertion_point(copy_constructor:person_data_fuzz)
}

void person_data_fuzz::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_person_data_fuzz_person_5fdata_2eproto.base);
  fuzz_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  fuzz_id_ = PROTOBUF_ULONGLONG(0);
}

person_data_fuzz::~person_data_fuzz() {
  // @@protoc_insertion_point(destructor:person_data_fuzz)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void person_data_fuzz::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  fuzz_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void person_data_fuzz::ArenaDtor(void* object) {
  person_data_fuzz* _this = reinterpret_cast< person_data_fuzz* >(object);
  (void)_this;
}
void person_data_fuzz::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void person_data_fuzz::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const person_data_fuzz& person_data_fuzz::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_person_data_fuzz_person_5fdata_2eproto.base);
  return *internal_default_instance();
}


void person_data_fuzz::Clear() {
// @@protoc_insertion_point(message_clear_start:person_data_fuzz)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    fuzz_name_.ClearNonDefaultToEmpty();
  }
  fuzz_id_ = PROTOBUF_ULONGLONG(0);
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* person_data_fuzz::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required uint64 fuzz_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_fuzz_id(&has_bits);
          fuzz_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required bytes fuzz_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_fuzz_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* person_data_fuzz::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:person_data_fuzz)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 fuzz_id = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_fuzz_id(), target);
  }

  // required bytes fuzz_name = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_fuzz_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:person_data_fuzz)
  return target;
}

size_t person_data_fuzz::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:person_data_fuzz)
  size_t total_size = 0;

  if (_internal_has_fuzz_name()) {
    // required bytes fuzz_name = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_fuzz_name());
  }

  if (_internal_has_fuzz_id()) {
    // required uint64 fuzz_id = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_fuzz_id());
  }

  return total_size;
}
size_t person_data_fuzz::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:person_data_fuzz)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required bytes fuzz_name = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_fuzz_name());

    // required uint64 fuzz_id = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_fuzz_id());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void person_data_fuzz::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:person_data_fuzz)
  GOOGLE_DCHECK_NE(&from, this);
  const person_data_fuzz* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<person_data_fuzz>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:person_data_fuzz)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:person_data_fuzz)
    MergeFrom(*source);
  }
}

void person_data_fuzz::MergeFrom(const person_data_fuzz& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:person_data_fuzz)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_fuzz_name(from._internal_fuzz_name());
    }
    if (cached_has_bits & 0x00000002u) {
      fuzz_id_ = from.fuzz_id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void person_data_fuzz::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:person_data_fuzz)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void person_data_fuzz::CopyFrom(const person_data_fuzz& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:person_data_fuzz)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool person_data_fuzz::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void person_data_fuzz::InternalSwap(person_data_fuzz* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  fuzz_name_.Swap(&other->fuzz_name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(fuzz_id_, other->fuzz_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata person_data_fuzz::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::person_data_fuzz* Arena::CreateMaybeMessage< ::person_data_fuzz >(Arena* arena) {
  return Arena::CreateMessageInternal< ::person_data_fuzz >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
